import type { Weapon } from "./types.ts";

export let characterClasses = [
	{
		classN: "Triggerman",
		maxHealth: 100,
		height: 100,
		width: 50,
		speed: 0.5,
		weaponIndexes: [0, 5],
		pWeapon: "Machine Gun",
		sWeapon: "Grenade Launcher",
		folderName: "triggerman",
		hasDown: false,
	},
	{
		classN: "Detective",
		maxHealth: 100,
		height: 100,
		width: 50,
		speed: 0.5,
		weaponIndexes: [1, 5],
		pWeapon: "Desert Eagle",
		sWeapon: "Grenade Launcher",
		folderName: "detective",
		hasDown: false,
	},
	{
		classN: "Hunter",
		maxHealth: 50,
		height: 100,
		width: 50,
		speed: 0.5,
		weaponIndexes: [2, 7],
		pWeapon: "Sniper",
		sWeapon: "Machine Pistol",
		folderName: "hunter",
		hasDown: true,
	},
	{
		classN: "Run 'N Gun",
		maxHealth: 100,
		height: 100,
		width: 50,
		speed: 0.6,
		weaponIndexes: [3],
		pWeapon: "Toy Blaster",
		sWeapon: "None",
		folderName: "billy",
		hasDown: false,
	},
	{
		classN: "Vince",
		maxHealth: 100,
		height: 100,
		width: 50,
		speed: 0.5,
		weaponIndexes: [4, 5],
		pWeapon: "Shotgun",
		sWeapon: "Grenade Launcher",
		folderName: "vinc",
		hasDown: true,
	},
	{
		classN: "Rocketeer",
		maxHealth: 120,
		height: 100,
		width: 50,
		speed: 0.4,
		name: "General Weiss",
		weaponIndexes: [6],
		pWeapon: "Rocket Launcher",
		sWeapon: "None",
		folderName: "rocketeer",
		hasDown: false,
	},
	{
		classN: "Spray N' Pray",
		maxHealth: 250,
		height: 100,
		width: 50,
		speed: 0.3,
		weaponIndexes: [8],
		pWeapon: "Minigun",
		sWeapon: "None",
		folderName: "mbob",
		hasDown: true,
	},
	{
		classN: "Arsonist",
		maxHealth: 100,
		height: 100,
		width: 50,
		speed: 0.5,
		weaponIndexes: [9],
		pWeapon: "Flamethrower",
		sWeapon: "None",
		folderName: "pyro",
		hasDown: true,
	},
	{
		classN: "Duck",
		maxHealth: 600,
		height: 100,
		width: 50,
		speed: 0.5,
		weaponIndexes: [],
		pWeapon: "Jump",
		sWeapon: "None",
		folderName: "boss2",
		hasDown: true,
	},
	{
		classN: "Nademan",
		maxHealth: 110,
		height: 100,
		width: 50,
		speed: 0.5,
		weaponIndexes: [5],
		pWeapon: "Nade Launcher",
		sWeapon: "None",
		folderName: "demo",
		hasDown: false,
	},
];
export function setCharacterClasses(newArr: typeof characterClasses) {
	characterClasses = newArr;
}
export const specialClasses = [
	{
		pWeapon: "???",
		sWeapon: "???",
		folderName: "boss1",
		hasDown: false,
	},
	{
		pWeapon: "???",
		sWeapon: "???",
		folderName: "boss2",
		hasDown: false,
	},
];

export const weapons: Weapon[] = [
	{
		name: "smg",
		weaponIndex: 0,
		dmg: 20,
		ammo: 24,
		maxAmmo: 24,
		reloadSpeed: 800,
		fireRate: 143,
		spread: [0],
		width: 30,
		length: 90,
		yOffset: 55,
		holdDist: 5,

		bSpeed: 6,
		bWidth: 6,
		bHeight: 12,
		bRandScale: [1, 1],
		cAcc: 12,
		maxLife: null,
		bulletsPerShot: 1,
		pierce: 0,
		pierceCount: 0,
		bounce: false,
		distBased: false,
		explodeOnDeath: false,
		bDist: 65,
		bTrail: 1,
		bSprite: 0,
		glowWidth: 25,
		glowHeight: 50,
		shake: 0.4,

		reloadTime: 0,
		spreadIndex: 0,
		lastShot: 0,
	},
	{
		name: "revolver",
		weaponIndex: 1,
		dmg: 50,
		ammo: 6,
		maxAmmo: 6,
		reloadSpeed: 1200,
		fireRate: 390,
		spread: [0],
		width: 30,
		length: 90,
		yOffset: 55,
		holdDist: 20,

		bSpeed: 6,
		bWidth: 8,
		bHeight: 16,
		bRandScale: [1, 1],
		cAcc: 12,
		maxLife: null,
		bulletsPerShot: 1,
		pierce: 0,
		pierceCount: 0,
		bounce: false,
		distBased: false,
		explodeOnDeath: false,
		bDist: 55,
		bTrail: 2,
		bSprite: 0,
		glowWidth: 25,
		glowHeight: 50,
		shake: 0.4,

		reloadTime: 0,
		spreadIndex: 0,
		lastShot: 0,
	},
	{
		name: "sniper",
		weaponIndex: 2,
		dmg: 100,
		ammo: 1,
		maxAmmo: 1,
		reloadSpeed: 1200,
		fireRate: 1170,
		spread: [0],
		width: 30,
		length: 90,
		yOffset: 55,
		holdDist: 0,

		bSpeed: 7,
		bWidth: 8,
		bHeight: 20,
		bRandScale: [1, 1],
		cAcc: 12,
		maxLife: null,
		bulletsPerShot: 1,
		pierce: 4,
		pierceCount: 0,
		bounce: false,
		distBased: false,
		explodeOnDeath: false,
		bDist: 75,
		bTrail: 3,
		bSprite: 0,
		glowWidth: 25,
		glowHeight: 50,
		shake: 0.4,

		reloadTime: 0,
		spreadIndex: 0,
		lastShot: 0,
	},
	{
		name: "toygun",
		weaponIndex: 3,
		dmg: 17,
		ammo: 8,
		maxAmmo: 8,
		reloadSpeed: 500,
		fireRate: 78,
		spread: [0],
		width: 30,
		length: 90,
		yOffset: 55,
		holdDist: 22,

		bSpeed: 5,
		bWidth: 6,
		bHeight: 12,
		bRandScale: [1, 1],
		cAcc: 12,
		maxLife: null,
		bulletsPerShot: 1,
		pierce: 0,
		pierceCount: 0,
		bounce: false,
		distBased: false,
		explodeOnDeath: false,
		bDist: 45,
		bTrail: 1,
		bSprite: 0,
		glowWidth: 25,
		glowHeight: 50,
		shake: 0.4,

		reloadTime: 0,
		spreadIndex: 0,
		lastShot: 0,
	},
	{
		name: "shotgun",
		weaponIndex: 4,
		dmg: 22,
		ammo: 3,
		maxAmmo: 3,
		reloadSpeed: 1000,
		fireRate: 455,
		spread: [-0.08, -0.02, 0.02, 0.08],
		width: 30,
		length: 90,
		yOffset: 55,
		holdDist: 5,

		bSpeed: 6,
		bWidth: 6,
		bHeight: 12,
		bRandScale: [1, 1],
		cAcc: 12,
		maxLife: null,
		bulletsPerShot: 4,
		pierce: 0,
		pierceCount: 0,
		bounce: false,
		distBased: false,
		explodeOnDeath: false,
		bDist: 65,
		bTrail: 1,
		bSprite: 0,
		glowWidth: 25,
		glowHeight: 50,
		shake: 0.4,

		reloadTime: 0,
		spreadIndex: 0,
		lastShot: 0,
	},
	{
		name: "grenades",
		weaponIndex: 5,
		dmg: 110,
		ammo: 1,
		maxAmmo: 1,
		reloadSpeed: 7500,
		fireRate: 92,
		spread: [0],
		width: 30,
		length: 90,
		yOffset: 55,
		holdDist: 5,

		bSpeed: 2,
		bWidth: 12,
		bHeight: 24,
		bRandScale: [1, 1],
		cAcc: 12,
		maxLife: 800,
		bulletsPerShot: 1,
		pierce: 0,
		pierceCount: 0,
		blastRadius: 150,
		bounce: true,
		distBased: false,
		explodeOnDeath: true,
		bDist: 50,
		bTrail: 0,
		bSprite: 0,
		glowWidth: 50,
		glowHeight: 100,
		shake: 0.4,

		reloadTime: 0,
		spreadIndex: 0,
		lastShot: 0,
	},
	{
		name: "rockets",
		weaponIndex: 6,
		dmg: 110,
		ammo: 1,
		maxAmmo: 1,
		reloadSpeed: 1200,
		fireRate: 0,
		spread: [0],
		width: 30,
		length: 90,
		yOffset: 55,
		holdDist: 0,

		bSpeed: 2,
		bWidth: 12,
		bHeight: 24,
		bRandScale: [1, 1],
		cAcc: 12,
		maxLife: null,
		bulletsPerShot: 1,
		pierce: 0,
		pierceCount: 0,
		blastRadius: 150,
		bounce: false,
		distBased: false,
		explodeOnDeath: true,
		bDist: 75,
		bTrail: 0,
		bSprite: 1,
		glowWidth: 50,
		glowHeight: 100,
		shake: 0.4,

		reloadTime: 0,
		spreadIndex: 0,
		lastShot: 0,
	},
	{
		name: "pistol",
		weaponIndex: 7,
		dmg: 12,
		ammo: 5,
		maxAmmo: 5,
		reloadSpeed: 1000,
		fireRate: 130,
		spread: [0],
		width: 30,
		length: 90,
		yOffset: 55,
		holdDist: 15,

		bSpeed: 5,
		bWidth: 6,
		bHeight: 12,
		bRandScale: [1, 1],
		cAcc: 12,
		maxLife: null,
		bulletsPerShot: 1,
		pierce: 0,
		pierceCount: 0,
		bounce: false,
		distBased: false,
		explodeOnDeath: false,
		bDist: 50,
		bTrail: 2,
		bSprite: 0,
		glowWidth: 25,
		glowHeight: 50,
		shake: 0.4,

		reloadTime: 0,
		spreadIndex: 0,
		lastShot: 0,
	},
	{
		name: "minigun",
		weaponIndex: 8,
		dmg: 10,
		ammo: 50,
		maxAmmo: 50,
		reloadSpeed: 1700,
		fireRate: 90,
		spread: [0, 0, 0],
		width: 30,
		length: 90,
		yOffset: 55,
		holdDist: 10,

		bSpeed: 5,
		bWidth: 6,
		bHeight: 12,
		bRandScale: [1, 1],
		cAcc: 12,
		maxLife: null,
		bulletsPerShot: 1,
		pierce: 0,
		pierceCount: 0,
		bounce: false,
		distBased: false,
		explodeOnDeath: false,
		bDist: 65,
		bTrail: 1,
		bSprite: 0,
		glowWidth: 25,
		glowHeight: 50,
		shake: 0.4,

		reloadTime: 0,
		spreadIndex: 0,
		lastShot: 0,
	},
	{
		name: "flamethrower",
		weaponIndex: 9,
		dmg: 10,
		ammo: 30,
		maxAmmo: 30,
		reloadSpeed: 1400,
		fireRate: 80,
		spread: [0, 0, 0],
		width: 30,
		length: 90,
		yOffset: 55,
		holdDist: 10,

		bSpeed: 1,
		bWidth: 24,
		bHeight: 48,
		bRandScale: [0, 0],
		cAcc: 12,
		maxLife: 600,
		bulletsPerShot: 2,
		pierce: 100,
		pierceCount: 0,
		bounce: true,
		distBased: false,
		explodeOnDeath: false,
		bDist: 90,
		bTrail: 0,
		bSprite: 2,
		glowWidth: 150,
		glowHeight: 300,
		shake: 0.4,

		reloadTime: 0,
		spreadIndex: 0,
		lastShot: 0,
	},
];

export const weaponNames = weapons.map((w) => w.name);
